version: "3.9"
services:
  go-app:
    build:
      context: ./go-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Замените на нужный порт
    depends_on:
      - postgres
      - clickhouse
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydatabase
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
volumes:
  postgres_data:
  clickhouse_data:
